dist: trusty
sudo: false

arch:
    - ppc64le    

language: c
env:
    - CC=clang-10
    - CXX=clang++-10    
  matrix:
    - VALGRIND=On SANITIZERS=Off
    - VALGRIND=Off SANITIZERS=Off
    - VALGRIND=Off SANITIZERS=On
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - valgrind
      - libasan4
      # - lib32asan4
      # currently not supported on travis-ci:
      # - libasan1
      # - libasan2
      # - libubsan0
      - clang-10
      - llvm
script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_CJSON_UTILS=On -DENABLE_VALGRIND="${VALGRIND}" -DENABLE_SAFE_STACK="${VALGRIND}" -DENABLE_SANITIZERS="${SANITIZERS}"
  - make
  - make test CTEST_OUTPUT_ON_FAILURE=On
