dist: trusty
sudo: false

arch:
    - ppc64le    

language: c
env:
  matrix:
    - VALGRIND=On SANITIZERS=Off
    - VALGRIND=Off SANITIZERS=Off
    - VALGRIND=Off SANITIZERS=On
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - valgrind
      - libasan4
      # - lib32asan4
      # currently not supported on travis:
      # - libasan1
      # - libasan2
      # - libubsan0
      - llvm
script:
  - mkdir build
  - cd build
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"  
  - sudo apt-get update  
  - sudo apt-get install -y clang-6.0  
  - cmake .. -DENABLE_CJSON_UTILS=On -DENABLE_VALGRIND="${VALGRIND}" -DENABLE_SAFE_STACK="${VALGRIND}" -DENABLE_SANITIZERS="${SANITIZERS}"
  - make
  - make test CTEST_OUTPUT_ON_FAILURE=On
